# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EncounterWidget.ui',
# licensing of 'ui/EncounterWidget.ui' applies.
#
# Created: Tue Dec 22 11:04:35 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_EncounterWidget(object):
    def setupUi(self, EncounterWidget):
        EncounterWidget.setObjectName("EncounterWidget")
        EncounterWidget.resize(602, 584)
        self.gridLayout = QtWidgets.QGridLayout(EncounterWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(EncounterWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previous = QtWidgets.QPushButton(self.frame)
        self.previous.setObjectName("previous")
        self.horizontalLayout_2.addWidget(self.previous)
        self.next = QtWidgets.QPushButton(self.frame)
        self.next.setObjectName("next")
        self.horizontalLayout_2.addWidget(self.next)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_index = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_index.setFont(font)
        self.label_index.setLineWidth(1)
        self.label_index.setAlignment(QtCore.Qt.AlignCenter)
        self.label_index.setObjectName("label_index")
        self.verticalLayout_2.addWidget(self.label_index)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_3.addWidget(self.label_name)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_spend = QtWidgets.QLabel(self.frame)
        self.label_spend.setObjectName("label_spend")
        self.verticalLayout.addWidget(self.label_spend)
        self.label_gain = QtWidgets.QLabel(self.frame)
        self.label_gain.setObjectName("label_gain")
        self.verticalLayout.addWidget(self.label_gain)
        self.label_time = QtWidgets.QLabel(self.frame)
        self.label_time.setObjectName("label_time")
        self.verticalLayout.addWidget(self.label_time)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 550))
        self.label.setMaximumSize(QtCore.QSize(16777215, 550))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/encounters/encounters/5.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(EncounterWidget)
        QtCore.QMetaObject.connectSlotsByName(EncounterWidget)

    def retranslateUi(self, EncounterWidget):
        EncounterWidget.setWindowTitle(QtWidgets.QApplication.translate("EncounterWidget", "Form", None, -1))
        self.previous.setText(QtWidgets.QApplication.translate("EncounterWidget", "previous", None, -1))
        self.next.setText(QtWidgets.QApplication.translate("EncounterWidget", "next", None, -1))
        self.label_index.setText(QtWidgets.QApplication.translate("EncounterWidget", "2/8", None, -1))
        self.label_name.setText(QtWidgets.QApplication.translate("EncounterWidget", "Bribing the Whelps", None, -1))
        self.label_spend.setText(QtWidgets.QApplication.translate("EncounterWidget", "Spend", None, -1))
        self.label_gain.setText(QtWidgets.QApplication.translate("EncounterWidget", "Gain:", None, -1))
        self.label_time.setText(QtWidgets.QApplication.translate("EncounterWidget", "Time: ", None, -1))

import unbroken_rc
